### ISSUE TITLE
Incompatability between pandas and scanpy versions?

### ISSUE THREAD

**Issue by katimbach** [mexchy1000/CellDART#5]
Hi, 

Sorry to open another issue, but after experiencing the problem with running the pipeline in R, I tried to switch to a jupyter notebook to do the analysis with my outputs. I was not able to download the tutorial data, as the `sc.datasets.visium_sge()` resulted in `HTTPError: HTTP Error 403: Forbidden`. Instead I used my own data (visium output from 10X, single cell data in h5ad format).

I read the single cell data in with anndata without issues, and was able to annotate the mitochondrial genes. However, when I try to calculate qc metrics it generates this error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_12785/4161002993.py in <module>
----> 1 sc.pp.calculate_qc_metrics(adata_embryo, qc_vars=['mt'], percent_top=None, log1p=False, inplace=True)

~/miniconda3/envs/CellDART/lib/python3.7/site-packages/scanpy/preprocessing/_qc.py in calculate_qc_metrics(adata, expr_type, var_type, qc_vars, percent_top, layer, use_raw, inplace, log1p, parallel)
    294         inplace=inplace,
    295         X=X,
--> 296         log1p=log1p,
    297     )
    298     var_metrics = describe_var(

~/miniconda3/envs/CellDART/lib/python3.7/site-packages/scanpy/preprocessing/_qc.py in describe_obs(adata, expr_type, var_type, qc_vars, percent_top, layer, use_raw, log1p, inplace, X, parallel)
    128             obs_metrics[f"total_{expr_type}_{qc_var}"]
    129             / obs_metrics[f"total_{expr_type}"]
--> 130             * 100
    131         )
    132     if inplace:

~/miniconda3/envs/CellDART/lib/python3.7/site-packages/pandas/core/ops/common.py in new_method(self, other)
     67         other = item_from_zerodim(other)
     68 
---> 69         return method(self, other)
     70 
     71     return new_method

~/miniconda3/envs/CellDART/lib/python3.7/site-packages/pandas/core/arraylike.py in __truediv__(self, other)
    114     @unpack_zerodim_and_defer("__truediv__")
    115     def __truediv__(self, other):
--> 116         return self._arith_method(other, operator.truediv)
    117 
    118     @unpack_zerodim_and_defer("__rtruediv__")

~/miniconda3/envs/CellDART/lib/python3.7/site-packages/pandas/core/series.py in _arith_method(self, other, op)
   5526             result = ops.arithmetic_op(lvalues, rvalues, op)
   5527 
-> 5528         return self._construct_result(result, name=res_name)
   5529 
   5530 

~/miniconda3/envs/CellDART/lib/python3.7/site-packages/pandas/core/series.py in _construct_result(self, result, name)
   2943         # We do not pass dtype to ensure that the Series constructor
   2944         #  does inference in the case where `result` has object-dtype.
-> 2945         out = self._constructor(result, index=self.index)
   2946         out = out.__finalize__(self)
   2947 

~/miniconda3/envs/CellDART/lib/python3.7/site-packages/pandas/core/series.py in __init__(self, data, index, dtype, name, copy, fastpath)
    428                 index = ibase.default_index(len(data))
    429             elif is_list_like(data):
--> 430                 com.require_length_match(data, index)
    431 
    432             # create/copy the manager

~/miniconda3/envs/CellDART/lib/python3.7/site-packages/pandas/core/common.py in require_length_match(data, index)
    530     if len(data) != len(index):
    531         raise ValueError(
--> 532             "Length of values "
    533             f"({len(data)}) "
    534             "does not match length of index "

ValueError: Length of values (1) does not match length of index (3101)
```
 It seems like this has been an error that has occurred previously with scanpy, and others attribute it to the pandas version present: https://github.com/scverse/scanpy/issues/2008. Is this a known problem? Is there any way to mediate it by changing the version of scanpy/pandas?

**Comment by katimbach** [comment]
Quickly following up, I was able to fix this problem by upgrading the scanpy version to  1.9.1, but it generated the following: 
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
celldart 0.0.1 requires h5py==2.10.0, but you have h5py 3.6.0 which is incompatible.
celldart 0.0.1 requires scanpy==1.5.1, but you have scanpy 1.9.1 which is incompatible.
```
Also, there is now a new error for the `sc.tl.leiden` line: 
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~/miniconda3/envs/CellDART/lib/python3.7/site-packages/scanpy/tools/_leiden.py in leiden(adata, resolution, restrict_to, random_state, key_added, adjacency, directed, use_weights, n_iterations, partition_type, neighbors_key, obsp, copy, **partition_kwargs)
    107     try:
--> 108         import leidenalg
    109     except ImportError:

ModuleNotFoundError: No module named 'leidenalg'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
/tmp/ipykernel_14653/316439528.py in <module>
      6 sc.pp.neighbors(adata_embryo, n_neighbors=10, n_pcs=30)
      7 sc.tl.umap(adata_embryo)
----> 8 sc.tl.leiden(adata_embryo, resolution = 0.5)
      9 sc.pl.umap(adata_embryo, color=['leiden'])

~/miniconda3/envs/CellDART/lib/python3.7/site-packages/scanpy/tools/_leiden.py in leiden(adata, resolution, restrict_to, random_state, key_added, adjacency, directed, use_weights, n_iterations, partition_type, neighbors_key, obsp, copy, **partition_kwargs)
    109     except ImportError:
    110         raise ImportError(
--> 111             'Please install the leiden algorithm: `conda install -c conda-forge leidenalg` or `pip3 install leidenalg`.'
    112         )
    113     partition_kwargs = dict(partition_kwargs)

ImportError: Please install the leiden algorithm: `conda install -c conda-forge leidenalg` or `pip3 install leidenalg`.
```

**Comment by bsungwoo** [comment]
Hello, @katimbach 

Thank you for reporting the error. Let me explain why the problem occurred.

As far as I know, ```HTTPError: HTTP Error 403: Forbidden``` error occurs in the specific scanpy version and it is a known problem, as some people have reported those issues. I recommend to directly download the Visium dataset from the 10X Genomics repository.

For the second problem, 
Could you skip all the lines in the cell except for the ```sc.pp.normalize_total(adata_cortex)```
All the lines in the cell are for clustering and visualization of the single-cell dataset and it is not related to the CellDART algorithm. Actually, the ```leidnalg``` package is required to run the code, but CellDART does not need the package. The conda environment used for the notebook example file and that for the CellDART function codes are different since they were uploaded by different collaborators. We are going to fix the issue.

**Comment by katimbach** [comment]
Hi @bsungwoo ,

When I skipped all lines but the normalization step, the error above still occurred- it was identified from that line isolated. It was fixed when I upgraded the version of scanpy. 

Additionally, I have found some more bugs in the code for generating the mixture from single cell data. Going back to the source code, it seems to be because if the single cell data is sparse (adata_cortex.X), the len() function will not be able to get the appropriate dimension: 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_15475/3404014604.py in <module>
----> 1 sc_mix, lab_mix = random_mix(mat_sc, lab_sc_num, nmix=6, n_samples=450)

/tmp/ipykernel_15475/2914611330.py in random_mix(Xs, ys, nmix, n_samples)
      8         fraction = fraction/np.sum(fraction)
      9         fraction = np.reshape(fraction, (nmix,1))
---> 10         randindex = np.random.randint(len(Xs), size=nmix)
     11         ymix = ys_[randindex]
     12         yy = np.sum(ymix*np.reshape(fraction, (nmix,1)), axis=0)

~/miniconda3/envs/CellDART/lib/python3.7/site-packages/scipy/sparse/base.py in __len__(self)
    289     # non-zeros is more important.  For now, raise an exception!
    290     def __len__(self):
--> 291         raise TypeError("sparse matrix length is ambiguous; use getnnz()"
    292                         " or shape[0]")
    293 

TypeError: sparse matrix length is ambiguous; use getnnz() or shape[0]
```
If I run instead `mat_sc = adata_embryo.X.todense()`, it fixes the issue. 

I was able to run the prediction pipeline to completion finally with my data, but at the end there are no spots being mapped at all to my images. I'm not sure if I used incorrect parameters- I mimicked what was in the` CellDART_example_mousebrain_markers.ipynb` file. Using the same data in de-convolution in Seurat, I obtained some populations mapped to the tissue, so I don't think it's a problem with the data (though there are not many spots compared to the example). When I view the pred_sp object after running the training, it gives:
```
array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=float32)
```

I'm also a bit unsure about when to run the `pred_cellf_celldart()` function after training, as it is not mentioned or used at all in the example. Could you provide some guidance regarding these steps?

**Comment by bsungwoo** [comment]
Hello, @katimbach 
I am not sure exactly what has brought you the result as 'nan'.  One possible cause of getting nan is dividing the counts by zero during the log transformation. (It may not directly cause an error, but in that case, nan is passed as an input) For the main function code and R wrap pipeline, I added the small value in the denominator to prevent the zero division error. Why don't you utilize pred_cellf_celldart in python instead of following the example code?

Regarding the explanation of the function, the ```pred_cellf_celldart python``` function is the compressed version of all the processes listed in the example code file. You may run the code directly with the line below.

``` Plain Text
from CellDART.pred_cellf_celldart import pred_cellf_celldart  
adata_sp = pred_cellf_celldart(adata_sp=adata_sp, adata_sc=adata_sc, count_from_raw = False,  
        　　　　　　　　　　　   gpu=True, celltype='celltype', num_markers=20,  
        　　　　　　　　　　　　 nmix=8, npseudo=20000, alpha=0.6, alpha_lr=5, batch_size=512,  
        　　　　　　　　　　　　 emb_dim=64, n_iterations=3000, init_train_epoch=10,  
        　　　　　　　　　　　　 outdir='./CellDART_output', return_anndata=True)
```

I am going to check the R wrap pipeline to investigate the cause of the problem.

**Comment by katimbach** [comment]
Hi @bsungwoo,

Thank you so much for your quick response! I will try it now with the new code and let you know- do I need to rebuild the environment from scratch for the effect to take place? For now I will continue in python while the R version gets sorted. 

Thanks again for all your help! Sorry for all of the questions, I am just looking forward to using this on my data!

Edit: I tried running the pred_cellf_celldart() but it generates the following:
```
  File "/tmp/ipykernel_17723/2044379773.py", line 4
    gpu=False, celltype='Cell_Cao', num_markers=20,
    ^
SyntaxError: invalid character in identifier
```
I unfortunately do not have GPU on my device so I must set this to False.

**Comment by bsungwoo** [comment]
@katimbach 
I think you don't need to re-install the conda environment. My preliminary guess is that the error is not due to the function but due to the syntax error. It is a character error so I think manually typing commas will solve the issue? Sometimes copying the comma will result in incorrect character conversion and python may not read the line.

**Comment by katimbach** [comment]
Hi @bsungwoo,

You were right, it was an indentation problem! I am now able to run the function without any problems, and now it has mapped cell types onto the tissue! Thank you so much again for your help, I really appreciate it.

**Comment by dsm-72** [comment]
Im still facing this problem. Ive also tried pinning pandas to 1.3.5 and scanty to 1.4.4

**Comment by bsungwoo** [comment]
Hello, @dsm-72 
1) Could you explain in more detail which line of the code produced an error and what the error message was?
2) Did you install the Conda environment using the command below?
```Plain Text
  conda create -n CellDART python=3.8  
  conda activate CellDART  
  pip install git+https://github.com/mexchy1000/CellDART.git 
```
3) Could you kindly list the installed libraries in the Conda environment and their versions using the command "pip list"?
