### ISSUE TITLE
Python 3.7

### ISSUE THREAD

**Issue by rimelof** [mexchy1000/CellDART#6]
Hello,

Thank you for making this package available. I am trying to install CellDART in a cluster that does not support anaconda well, and only has python 3.8.2 and 3.9.8. When I try to install I get the error
`ERROR: Could not find a version that satisfies the requirement tensorflow==1.14.0 (from celldart)`
and proceeds to list several version of tensorflow available, from 2.5.0 to 2.9.1.

My understanding is that only newer version of tensorflow are available to python 3.9.8. In that case, would it be possible to relax the tensorflow dependency so I can installed on this system? 

Thank you!

**Comment by rimelof** [comment]
Hi,

I got it to work with anaconda in another system, but now I am facing an issue with forward compatibility of the sc reference object as described here: https://github.com/scverse/anndata/issues/698.

It would be great if CellDART could be installed with a newer python.

Thank you!

**Comment by bsungwoo** [comment]
@rimelof 

Hello, thank you for reporting an error. There is a compatibility issue between TensorFlow 1.X and 2.X version codes and I have to modify the codes to fit the new format. I am going to work on this, but it may take some time for me to convert the codes.

Regarding the forward compatibility issues of the AnnData object, could you show me the error message and version of anndata package that you are currently using? Did the error occur while implementing the function read_h5ad? If the error message was identical to the one presented on https://github.com/scverse/anndata/issues/698, then could you drop the 'layer' in the AnnData object and try again?

I am going to upgrade the package to the newer Python version.

**Comment by bsungwoo** [comment]
@rimelof 

Hello, I updated the code as explained above. Could you reinstall the conda environment and implement the python function?
As far as I understand, the second issue regarding the forward compatibility will be resolved since I updated the anndata version from 0.7.X to 0.8.0.

Please tell us how the solution worked out. Thanks for reporting the issue.

**Comment by rimelof** [comment]
I got a successful installation and could load the library in python 3.9.8. 

Thank you for the update!
